version: '3'

services:
  spring-boot-rest-api-app:
    image: spotapi-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      – 5000:5000
    volumes:
      – /data/spotapi
